version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
  dev-deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Dump Google Cloud Credentials to file
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run:
          name: Add Google Cloud Service Account credentials to GCloud SDK
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run:
          name: Set GCloud project
          command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - deploy:
          name: Deploy to Google App Engine
          command: gcloud app deploy app-stage.yaml --quiet

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - dev-deploy:
          requires:
            - test
          filters:
            branches:
              only: /^dev$/